# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Gradelevel.create!([
  { :name => "Preschool", :abbrev => "Pre-K", :number => -1, :created_at => "2014-02-06 20:27:31", :updated_at => "2014-02-06 20:27:31" },
  { :name => "Kindergarten", :abbrev => "K", :number => 0, :created_at => "2014-02-06 20:27:53", :updated_at => "2014-02-06 20:27:53" },
  { :name => "First", :abbrev => "1st", :number => 1, :created_at => "2014-02-06 20:28:00", :updated_at => "2014-02-06 20:28:00" },
  { :name => "Second", :abbrev => "2nd", :number => 2, :created_at => "2014-02-06 20:28:06", :updated_at => "2014-02-06 20:28:06" },
  { :name => "Third", :abbrev => "3rd", :number => 3, :created_at => "2014-02-06 20:28:12", :updated_at => "2014-02-06 20:28:12" },
  { :name => "Fourth", :abbrev => "4th", :number => 4, :created_at => "2014-02-06 20:28:19", :updated_at => "2014-02-06 20:28:19" },
  { :name => "Fifth", :abbrev => "5th", :number => 5, :created_at => "2014-02-06 20:28:29", :updated_at => "2014-02-06 20:28:29" },
  { :name => "Sixth", :abbrev => "6th", :number => 6, :created_at => "2014-02-06 20:28:39", :updated_at => "2014-02-06 20:28:39" },
  { :name => "Seventh", :abbrev => "7th", :number => 7, :created_at => "2014-02-06 20:28:55", :updated_at => "2014-02-06 20:28:55" },
  { :name => "Eighth", :abbrev => "8th", :number => 8, :created_at => "2014-02-06 20:29:06", :updated_at => "2014-02-06 20:29:06" },
  { :name => "Ninth", :abbrev => "9th", :number => 9, :created_at => "2014-02-06 20:29:13", :updated_at => "2014-02-06 20:29:13" },
  { :name => "Tenth", :abbrev => "10th", :number => 10, :created_at => "2014-02-06 20:29:21", :updated_at => "2014-02-06 20:29:21" },
  { :name => "Eleventh", :abbrev => "11th", :number => 11, :created_at => "2014-02-06 20:29:30", :updated_at => "2014-02-06 20:29:30" },
  { :name => "Twelfth", :abbrev => "12th", :number => 12, :created_at => "2014-02-06 20:29:39", :updated_at => "2014-02-06 20:29:39" }
])



LessonEntryset.create!([
  { :name => "Trunk", :parent_id => nil, :lft => 1, :rgt => 24, :depth => 0, :created_at => "2014-01-23 01:50:04", :updated_at => "2014-01-23 01:50:04" },
  { :name => "Outcomes", :parent_id => 1, :lft => 2, :rgt => 13, :depth => 1, :created_at => "2014-01-23 01:50:21", :updated_at => "2014-01-23 01:56:08" },
  { :name => "Evidence", :parent_id => 1, :lft => 14, :rgt => 19, :depth => 1, :created_at => "2014-01-23 01:50:54", :updated_at => "2014-01-23 01:56:14" },
  { :name => "Plan", :parent_id => 1, :lft => 20, :rgt => 23, :depth => 1, :created_at => "2014-01-23 01:51:05", :updated_at => "2014-01-23 01:56:18" },
  { :name => "Goals", :parent_id => 2, :lft => 3, :rgt => 4, :depth => 2, :created_at => "2014-01-23 01:51:23", :updated_at => "2014-01-23 01:55:57" },
  { :name => "Understandings", :parent_id => 2, :lft => 5, :rgt => 6, :depth => 2, :created_at => "2014-01-23 01:51:41", :updated_at => "2014-01-23 01:55:42" },
  { :name => "Questions", :parent_id => 2, :lft => 7, :rgt => 8, :depth => 2, :created_at => "2014-01-23 01:52:20", :updated_at => "2014-01-23 01:55:30" },
  { :name => "Knowledge", :parent_id => 2, :lft => 9, :rgt => 10, :depth => 2, :created_at => "2014-01-23 02:00:05", :updated_at => "2014-01-23 02:00:05" },
  { :name => "Skills", :parent_id => 2, :lft => 11, :rgt => 12, :depth => 2, :created_at => "2014-01-23 02:00:22", :updated_at => "2014-01-23 02:00:22" },
  { :name => "Performance Task", :parent_id => 3, :lft => 15, :rgt => 16, :depth => 2, :created_at => "2014-01-23 02:01:37", :updated_at => "2014-01-23 02:01:37" },
  { :name => "Other Evidence", :parent_id => 3, :lft => 17, :rgt => 18, :depth => 2, :created_at => "2014-01-23 02:11:40", :updated_at => "2014-01-23 02:11:40" },
  { :name => "Hook", :parent_id => 4, :lft => 21, :rgt => 22, :depth => 2, :created_at => "2014-01-23 02:25:57", :updated_at => "2014-01-23 02:25:57" }
])



LessonTemplate.create!([
  { :name => "Unit Template", :description => "Ben's First Attempt at a Unit Template", :rows => 8, :cols => 2, :created_at => "2014-01-23 02:37:34", :updated_at => "2014-01-23 13:34:16" }
])



StandardDomain.create!([
  { :subject_id => 2, :standardkind_id => 1, :name => "Anchor Standards (College and Career Readiness)", :abbrev => "CCRA", :created_at => "2014-02-06 22:10:54", :updated_at => "2014-02-06 22:10:54" },
  { :subject_id => 2, :standardkind_id => 1, :name => "Reading: Literature", :abbrev => "RL", :created_at => "2014-02-06 22:13:24", :updated_at => "2014-02-06 22:13:24" },
  { :subject_id => 2, :standardkind_id => 1, :name => "Reading: Informational Text", :abbrev => "RI", :created_at => "2014-02-06 22:13:53", :updated_at => "2014-02-06 22:13:53" },
  { :subject_id => 2, :standardkind_id => 1, :name => "Reading: Foundational Skills", :abbrev => "RF", :created_at => "2014-02-06 22:14:20", :updated_at => "2014-02-06 22:14:20" },
  { :subject_id => 2, :standardkind_id => 1, :name => "Writing", :abbrev => "W", :created_at => "2014-02-06 22:15:09", :updated_at => "2014-02-06 22:15:09" },
  { :subject_id => 2, :standardkind_id => 1, :name => "Speaking & Listening", :abbrev => "SL", :created_at => "2014-02-06 22:15:30", :updated_at => "2014-02-06 22:15:30" },
  { :subject_id => 2, :standardkind_id => 1, :name => "Language", :abbrev => "L", :created_at => "2014-02-06 22:15:52", :updated_at => "2014-02-06 22:15:52" },
  { :subject_id => 2, :standardkind_id => 1, :name => "History / Social Studies", :abbrev => "RH", :created_at => "2014-02-06 22:16:52", :updated_at => "2014-02-06 22:16:52" },
  { :subject_id => 2, :standardkind_id => 1, :name => "Science & Technical Subjects", :abbrev => "RST", :created_at => "2014-02-06 22:17:53", :updated_at => "2014-02-06 22:17:53" },
  { :subject_id => 2, :standardkind_id => 1, :name => "Writing (History / Social Studies, Science & Technical Subjects)", :abbrev => "WHST", :created_at => "2014-02-06 22:18:46", :updated_at => "2014-02-06 22:18:46" }
])



Standardkind.create!([
  { :name => "Common Core", :created_at => "2014-02-06 22:09:26", :updated_at => "2014-02-06 22:09:26" }
])



Subject.create!([
  { :name => "Math", :created_at => "2014-02-06 20:26:59", :updated_at => "2014-02-06 20:26:59" },
  { :name => "English Language Arts / Literacy", :created_at => "2014-02-06 20:27:14", :updated_at => "2014-02-06 20:27:14" }
])


